name: Deploy para Hostinger via FTP

on:
  push:
    branches:
      - main  # ou outra branch que você usa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Enviar arquivos via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}/
        local-dir: ./
        exclude: |
          **/.git*
          **/.github*
          **/tests*
          writable/cache/*
          writable/logs/*